version: "2.1"

services:

  app:
    # Build application using Dockerfile contained in application subfolder
    build: ./application
    # Name image
    image: registry.eu-gb.bluemix.net/thesis/ethercis-app
    # Map application container port 8080 to Docker port 8080
    ports:
      - "8888:8080"
    # Do not start application container until postgres service is started
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    # Build database using Dockerfile contained in postgres subfolder
    build: ./postgres
    # Name image
    image: registry.eu-gb.bluemix.net/thesis/ethercis-db
